In [1]:
from sklearn.model_selection import train_test_split

# Multilayer Perceptron

In [2]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
# Load the data
data = pd.read_csv('procesed_imgdata_32x32.csv')

C:\Users\Pankaj\AppData\Local\Temp\ipykernel_20476\789716297.py:2: DtypeWarning: Columns (1024) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('procesed_imgdata_32x32.csv')


In [4]:
# Split the data into features and target
X = data.iloc[:,:-3]
y = data["labelsEnc"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [5]:
clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000)

In [6]:
clf.fit(X_train, y_train)

MLPClassifier(max_iter=1000)

In [7]:
y_pred = clf.predict(X_test)
accuracy = clf.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9825249060917851


In [8]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix:\n", cm)

Confusion matrix:
 [[290   0   0 ...   0   0   0]
 [  0 291   0 ...   0   0   0]
 [  0   0 309 ...   0   0   0]
 ...
 [  0   1   0 ... 318   0   0]
 [  0   0   0 ...   0 291   0]
 [  0   0   0 ...   0   0 340]]


In [9]:
cr = classification_report(y_test, y_pred)
print("Classification report:\n", cr)

Classification report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       291
           1       0.99      1.00      0.99       292
           2       0.99      1.00      1.00       309
           3       1.00      1.00      1.00       323
           4       1.00      0.99      1.00       308
           5       1.00      1.00      1.00       298
           6       1.00      0.99      0.99       307
           7       1.00      1.00      1.00       361
           8       1.00      1.00      1.00       311
           9       1.00      1.00      1.00       340
          10       0.98      0.91      0.94       298
          11       0.91      0.97      0.94       322
          12       0.99      0.94      0.97       331
          13       0.91      0.94      0.93       326
          14       0.97      0.97      0.97       317
          15       0.91      0.93      0.92       315
          16       0.96      0.93      0.94       325
   

In [10]:
import pickle
with open('mlp_model.pkl', 'wb') as file:
    pickle.dump(clf, file)